name: Deploy Backend

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: self-hosted
        name: Deploy Backend

        strategy:
            matrix:
                node-version: [22.x]

        if: github.ref == 'refs/heads/master'
        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 22.x

            - name: Copy environment
              run: cp /home/vinicius/apps/environment/.env api/.env

            - name: Install dependencies
              run: npm install
              working-directory: api

            - name: Generate prismaclient
              run: npx prisma generate
              working-directory: api

            - name: Build project
              run: npm run build
              working-directory: api

            - name: Clean old app
              run: rm -rf /home/vinicius/apps/fincheck-api/*

            - name: Copy build
              run: cp -r dist/* /home/vinicius/apps/fincheck-api
              working-directory: api

            - name: Copy prisma
              run: cp -r prisma /home/vinicius/apps/fincheck-api
              working-directory: api

            - name: Copy dependencies
              run: cp -r node_modules /home/vinicius/apps/fincheck-api
              working-directory: api

            - name: Restart service
              run: pm2 reload all
