name: Deploy Frontend

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: self-hosted
        name: Deploy Frontend

        strategy:
            matrix:
                node-version: [22.x]

        if: github.ref == 'refs/heads/master'
        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm install
              working-directory: frontend

            - name: Build project
              run: npm run build
              working-directory: frontend

            - name: Copy build to app folder
              run: cp -r dist/* /home/vinicius/apps/fincheck-web
              working-directory: frontend
